"""Live paired decoder experiment on retained, identical trained heads."""
import argparse,json,shutil,subprocess,sys,time
from pathlib import Path
P=Path(__file__).resolve().parents[1];sys.path[:0]=[str(P),str(P/'tier1')]
from storage import sha
from insula.entry import launch_plan
C=Path.home()/'.cache/waystone/waymo-perception';W=C/'scientific-processing';a=argparse.ArgumentParser();a.add_argument('--run-id',required=True);a.add_argument('--step',type=int,required=True);args=a.parse_args();R=C/'insula'/('tier1-heading-'+args.run_id);R.mkdir();source=R/'source';source.mkdir()
for folder in ['pipeline','gpu','cohort','tier1','research']:shutil.copytree(P/folder,source/folder,ignore=shutil.ignore_patterns('__pycache__'))
f=json.loads((P/'research/tier1-allclass-fixture-verified.json').read_text());scene,t=f['identity'].split(':');relative=f'{scene}/{t}/producer';native=W/'balanced16-native-v2';inputs=R/'inputs';inputs.mkdir();frame={'identity':f['identity'],'relative_directory':relative,'sha256':{n:sha(native/relative/n) for n in ['observations.npz','targets.npz','report.json']},'physical_sha256':f['physical_sha256'],'boxes_sha256':f['boxes_sha256']};manifest={'frames':[frame]};(inputs/'manifest.json').write_text(json.dumps(manifest));pins={str(p):sha(p) for p in source.rglob('*') if p.is_file()};heads=W/'tier1-overfit20261002a-baseline'/f'checkpoint-{args.step:04d}';headhash=sha(heads/'heads-00.npz');out=W/('tier1-heading-'+args.run_id);out.mkdir();checks=[];roots={'cpu':C/'insula/rootfs-v2','metrics':C/'metrics-rootfs'}
def stage(name,root,src,directory,worker,extra=[]):
 directory.mkdir();cmd=launch_plan(roots[root],source,src,directory,['python','/experiment/'+worker]);i=cmd.index('--');cmd[i:i]=['--ro-bind',str(inputs),'/tmp/inputs','--ro-bind',str(native),'/tmp/native','--ro-bind',str(W/'balanced16-physical-v2'),'/tmp/physical','--ro-bind',str(W/'balanced16-labels-v2'),'/tmp/boxes','--ro-bind',str(source/'cohort'),'/tmp/workers',*extra];start=time.monotonic()
 with (directory/'live.log').open('w') as log:r=subprocess.run(cmd,stdout=log,stderr=subprocess.STDOUT,timeout=1800)
 assert r.returncode==0,(name,str(directory/'live.log'));checks.append({'name':name,'command':cmd,'exit_code':0,'elapsed_seconds':time.monotonic()-start});assert sha(heads/'heads-00.npz')==headhash and all(sha(p)==h for p,h in pins.items());print('PASS',name,flush=True)
prepared=out/'prepared';scored=out/'scored';stage('prepare-v3','cpu',heads,prepared,'tier1/prepare_v3.py');stage('score-v3','metrics',prepared,scored,'cohort/metrics.py');values=json.loads((scored/'check.json').read_text());receipt={'manifest':manifest,'validation':values,'artifacts':{str(p):sha(p) for directory in [prepared,scored] for p in directory.iterdir() if p.is_file()}};rp=out/'score-receipt.json';rp.write_text(json.dumps(receipt,indent=2));expected=out/'expected.json';expected.write_text(json.dumps({'receipt':receipt,'receipt_sha256':sha(rp)}));extra=['--ro-bind',str(scored),'/tmp/scored','--ro-bind',str(heads),'/tmp/heads','--ro-bind',str(expected),'/tmp/expected.json','--ro-bind',str(rp),'/tmp/score-receipt.json'];stage('literal-v3-proposals','cpu',prepared,out/'proposal-audit','tier1/audit_proposals_v3.py',extra);stage('independent-export-native-replay','metrics',prepared,out/'metric-audit','cohort/audit_metrics.py',extra)
legacy=json.loads((heads.parent/'scoring'/str(args.step)/'scored/check.json').read_text());report={'step':args.step,'identical_heads_sha256':headhash,'legacy_LEVEL2_per_class':legacy['LEVEL2_per_class'],'canonical_direction_LEVEL2_per_class':values['LEVEL2_per_class'],'checks':checks,'source_sha256':pins,'artifacts':{str(p):sha(p) for p in out.rglob('*') if p.is_file()},'runtime_locks':{k:json.loads(Path(str(v)+'.lock.json').read_text()) for k,v in roots.items()},'scope':'paired evaluation-only heading decoder correction; identical trained heads, all73nativeGT; not a new training run'};(P/'research'/('tier1-heading-'+args.run_id+'-verified.json')).write_text(json.dumps(report,indent=2));print('PAIRED NATIVE',report['legacy_LEVEL2_per_class'],report['canonical_direction_LEVEL2_per_class'],flush=True)
