# Approved execution order — 2026-10-03

The user approved this ordering as steering for the existing research goal. Preserve ongoing implementation, retained checkpoints, frozen recipes and historical evidence.

1. Complete the resource admission gate before new optimizer updates: immutable seven-stage checkpoint companions; exact raw proof/source/log HDFS readback and live recovery; bounded legacy-stage verification with unchanged native outputs and GPU state; and independent live Insula verification of the complete runner. Partial preparation receipts do not admit continuation.
2. Resume the retained four-case balanced16 sweep in its frozen order: `baseline`, `residual_bev`, `class_balanced`, `prior_bias`. The baseline has retained checkpoints at 0 and 1,000 updates; its next prescribed sample is 2,000. Resume original optimizer, RNG, sampler and elapsed-time state rather than restarting. Preserve all 1,279 native evaluation ground truths, frozen targets and V3 decoder. Report exact per-frame visits and per-class learning.
3. Queue ticket 42, the measurement-indexed object failure ledger, followed by ticket 43, the frozen-weight normalization diagnostic. Their read-only work may proceed separately using admitted evidence. Any GPU execution must use the existing serialized experiment lock and separate diagnostic outputs; it must not change sweep weights, optimizer state, buffers, targets or sampler. Pillar LN is conditional on ticket 43 findings and requires a separately frozen matched treatment.
4. Continue ticket 41 from independently admitted 41.1 contract/runtime into 41.2 ownership. Independently verify zero uncovered eligible GT, unique reservations and preserved unreserved legacy assignments against the frozen cohort. Keep all native evaluation GT. This is a separate target-association investigation; its ownership or target changes must not enter the four-case sweep.

Every implementation milestone requires independent live Insula verification. Preserve training caps of 32,000 updates and 7,200 synchronized seconds, native scoring bound of 14,400 seconds and host bound of 14,700 seconds, and every-class LEVEL2 APH >= 0.8 at two consecutive prescribed samples including terminal. Preserve GPU 8 GiB, RSS 16 GiB, raw-data 2 GiB, scientific storage 15 GiB, case 2 GiB, keep-two recovery and the 2 GiB new-case reserve. Exact HDFS readback, live recovery and independent archive-union verification must precede local release.

Residual/masked-pooling/point-attention follow-ups remain controlled comparisons. Range and sparse directions remain exploratory. Fitting diagnostics do not close held-out detection, segmentation/SAM or forecasting research.

At recording: resource stage attachment is independently reviewed and landed; checkpoint companions and the archive worker pass 34 live CPU Insula test groups. Full resource admission, HDFS closure and legacy bounded revalidation remain open. No new training or local payload release is claimed.
