module(name = "sureal", version = "0.0.0")

bazel_dep(name = "rules_python", version = "2.4.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "shellcheck_linux_x86_64",
    build_file_content = """exports_files(["shellcheck"])""",
    sha256 = "8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198",
    strip_prefix = "shellcheck-v0.11.0",
    urls = ["https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.linux.x86_64.tar.xz"],
)

http_archive(
    name = "ruff_linux_x86_64",
    build_file_content = """exports_files(["ruff"])""",
    sha256 = "ed8ba4cac0c6dfc1c0e9c6c720daa5ea404a3bff0497a95d6e25293a7910e903",
    strip_prefix = "ruff-x86_64-unknown-linux-gnu",
    urls = ["https://github.com/astral-sh/ruff/releases/download/0.6.9/ruff-x86_64-unknown-linux-gnu.tar.gz"],
)

local_runtime_repo = use_repo_rule(
    "@rules_python//python/local_toolchains:repos.bzl",
    "local_runtime_repo",
)

local_runtime_toolchains_repo = use_repo_rule(
    "@rules_python//python/local_toolchains:repos.bzl",
    "local_runtime_toolchains_repo",
)

local_runtime_repo(
    name = "rootfs_python3",
    interpreter_path = "/usr/local/bin/python",
    on_failure = "fail",
)

local_runtime_toolchains_repo(
    name = "rootfs_python_toolchains",
    runtimes = ["rootfs_python3"],
)

register_toolchains("@rootfs_python_toolchains//:all")
