# Waymo AV perception research retrospective: scientific and engineering evidence

**Cutoff:** 2026-10-04 18:56:47 UTC. **Repository evidence:** immutable snapshot `a553645ef22761aa7708abf1ee109952a6cd2c38`. This retrospective audits public user/assistant messages, execution metadata and errors in the local session-history projection, and reconciles claims against that Git snapshot. It excludes private reasoning and credentials. Session citations use thread / turn / item IDs and UTC timestamps; these are receipts for what was said, while the pinned repository receipts own scientific acceptance.

## Finding

The program made substantial, unusually reproducible engineering progress and reached real detector-fitting results. It did **not** answer the main generalization questions. The strongest current scientific decision is to retain compact pillar/dense-GN plus clipped Adam as a reference; separate foreground supervision/assignment, normalization state and per-frame exposure effects; retain point attention as a matched-control candidate; and keep range fusion and the current sparse-transformer recipe exploratory. This is a prioritization decision, not architecture adoption. No held-out winner or multi-seed comparison exists at cutoff.

The early two-scene tracer and the later 103-scene geometry work are distinct achievements. The first closed acquisition, native table/schema integrity and deterministic metadata processing. R0 then independently reconstructed real range/pose geometry for the two-scene fixture inside the locked environment. Later data gates extended shape, semantic and point-grid admission over 103 selected scenes. None of these data receipts alone establishes a detector, segmentation, mask-transfer or forecasting result.

## What was established

### Acquisition, TF-free processing, and geometric tracer

The initial tracer solved the access problem by selecting two compact validation scenes with all 17 available component families, acquiring 34 files (about 1.2 GB), verifying GCS and HDFS checksums, and running offline without TensorFlow or mounted GCS credentials. Its deterministic pass covered 397 frames and 143,625 native component records. It preserved 337 camera-to-LiDAR references that had no same-frame LiDAR box as unresolved instead of joining to a different frame. This was a successful *ingestion/schema* tracer, not yet reconstruction of point geometry. Session receipt: thread `01a0ee75-f519-7c80-b3c2-dc39d09e0b24`, turn `01a0ee93-ac19-7c81-8ebe-c438d6f904e3`, item `msg_031c4f878d2513b9016abc13964e7887d28bfaba74e83bc02d`, 2026-09-29 19:37:58 UTC (two-scene closeout); early evidence of the unresolved same-frame references is item `msg_031c4f878d2513b9016abc10d5788487d29a160433ce9c5581`, 2026-09-29 19:26:13 UTC.

Tickets 01–06 subsequently completed R0 for that fixture. The pinned closeout reports: locked CPU Insula boundary (M0); 143,625 native rows from 34 files / 17 families (M1); 11 live analytic/manifold/boundary/covariance geometry fixtures (M2); 397 frames, 3,970 sensor/return records and 71,891,534 positive finite range points (M3); maximum sampled scalar-coordinate discrepancy `1.5756285165480222e-11 m`; 131 inspection artifacts across four labeled/unlabeled frames, 20 camera views and 40 LiDAR-return views (M4); and byte-identical deterministic native/geometry/manifest results on the repeat (M5). Camera overlays deliberately use supplied projections; the evidence does not claim independent rolling-shutter or moving-point projection. Other LiDAR returns remain uncompensated. These are engineering/geometry proofs on two validation scenes, not a trained-model result or held-out benchmark reproduction. Sources: `experiments/waymo-perception/research/r0-geometric-insula.md`, `r0-execution-ledger.md`, M0–M5 verified records at the pinned commit. The first tracer's public completion is cited above; exact acceptance comes from these pinned records.

Later work extended data admission beyond the R0 fixture: all 64 training box sources replayed; semantics were reconciled across 103 scenes and 478,579,462 eligible point labels; native shape recovery admitted 203,850 return records across 103 scenes; and full-support point-to-native-grid replay admitted 3,513,295,187 points across those scenes. Camera lifecycle receipts separately reconcile all 103 scenes. Aggregates are explicitly host rehashes of individual independent live admissions where stated; do not describe the rollup as a new independent live aggregate. Receipts: `research-task-index.md` and linked `training-box-full64-replay-verified.json`, `scientific-semantic-full103-verified.json`, `scientific-native-shape-full103-retained-audit.json`, `scientific-camera-full103-verified.json`, `point-grid-full103-and-overfit-box-retained-audit.json`. These materially close data prerequisites, while ticket 07's protocol freeze and scientific evaluations remain open.

### Evaluators, protocol and detection baselines

Tickets 08 and 09 are verified: locked single-device Torch runtime and TensorFlow-free native 3D AP/APH plus LiDAR semantic evaluator. The task index explicitly leaves camera 2D, LET and panoptic tracking for later gates. Ticket 07 remains open: model/cohort, sampling/loss, resource budgets, acceptance thresholds and comparisons need a frozen protocol before affected experiments. The overall goal document likewise keeps tickets 10–22 open. Thus successful runtime/evaluator engineering should not be counted as a baseline model result.

Ticket 35's fixed-batch all-class sweep is substantial positive *learnability* evidence. It runs 15 trainable treatments plus a cap-equivalence control on one selected 73-object training frame; all 15 pass sustained four-class native overfit with full trajectory/model/Adam/RNG replay and final live closure. The compact reference reaches the all-class gate at 500 updates and confirms at 750. The 2026-10-03 analysis reconciles 23 trained rows as 15 tier-1 plus 8 expanded-sweep treatments; seven of the eight expanded treatments fit, and the sparse transformer is censored/negative at its 10,000-update cap. These are all training-frame diagnostics. The 73-object frame lacks scene diversity and cannot show generalization.

Ticket 33's balanced16 baseline and residual runs both reach 2,000 updates, pass exact 16-frame checkpoint/Adam replay and 48 independent loss-equation checks, then fail the prescribed all-class native quality gate. This is an informative negative result, not proof that all architectures fail on mixtures. The historical balanced16 run allocated exactly 125 visits per frame at 2,000 updates, whereas single-frame controls generally used 500–750 visits. The latest four-case sustained study was still gated at cutoff: baseline remained at 0/1,000 and no follow-on optimizer update was admitted. The approved order requires resource/HDFS/continuation gates first; so don’t present its planning work as a fresh run.

### Why the early fitting signal was ambiguous, and the right follow-up

The most useful diagnosis separates model learnability, mixture fitting, and generalization:

* The selected frame had 338/30/16/6 positive anchors for vehicle/pedestrian/sign/cyclist (vehicle 86.7% of positives). At update 300, baseline APH was `.887/.730/.463/0`, while class-balanced positive focal weighting gave `.468/.997/.865/.997`: rare classes improved while vehicles regressed. Both later passed at 500 and confirmed at 750; weighting was not shown to fit all classes faster. Foreground-prior bias also improved early foreground behavior but confirmed later, at 1,000.
* On balanced16, total loss fell `1564.662 → 1.073`, but background focal fell `1558.205 → .0718` and positive-anchor focal only `.7084 → .2417`, while native class scores remained poor. Aggregate loss was therefore a weak success signal.
* Normalization is a real candidate cause. On the selected frame at update 500, full-BN evaluation loss was `2.010` versus `.0644` with batch statistics. A frozen-weight BN recalibration earlier changed loss `.05814 → .00748` and historical APH `.738 → .864` with zero optimizer updates. That causal intervention applies to the earlier 17-object case only. The GN-backbone baseline still includes pillar BN: balanced16 terminal eval loss `1.0732` versus `.2950` with restored current-frame buffers; native quality under that counterfactual has not been established.
* Coverage is separate from representation. In balanced16, 29 signs and one pedestrian had positive maximum overlap but lost all positive anchors to assignment conflicts (mostly same class). The covered-target ideal sign APH is `.759399`; all ROI-eligible targets' ideal sign APH is `.868421`, against unchanged full native ground truth. This motivates the separately specified A0–A3 association study, not a claim of a universal detector ceiling.
* At equal 750 updates, point attention reached vehicle/sign APH `.984/.927`, versus `.880/.811` for an equal-parameter MLP control: a promising local mechanism comparison, still a single frame/seed. Range fusion reached vehicle `.946` versus `.999` for zero-range control, with no faster fit. The sparse occupied-token transformer reached vehicle `.742` after 10,000 updates while also changing capacity (4.847M to 2.065M) and dense spatial propagation, so this recipe does not isolate one hypothesis.

The published recommendation (analysis, evidence audit, numerical JSON and curves) is to retain compact pillar/dense-GN clipped-Adam reference and resolve assignment, normalization and exposure first; test attention with repeats/failure IDs/held-out benefit; keep range and sparse results exploratory; require held-out segment splits, multiple seeds, class/distance/support reporting, and measured resource costs before promotion. Sources: `research/2026-10-03-initial-experiments-analysis.md`, matching `...-evidence-audit.md`, `...-analysis.json`, approved execution order, task tickets 33–43 and journal entries 86–103. Session receipt for the analysis and central interpretation: thread `01a10073-9fd4-7361-b4f2-e7034230800a`, turn `01a10076-d095-7e51-942e-d9f9b4aa6851`, item `msg_031c4f878d2513b9016ac0a9053f0487d29dd8485080c293f3`, 2026-10-03 07:04:37 UTC; prior details item `msg_031c4f878d2513b9016ac0a23a927887d2a3cd93ec5da05340`, 06:35:38 UTC; cross-curve interpretation item `msg_031c4f878d2513b9016ac0a3e153ac87d2b7c7b364160e6aed`, 2026-10-03 06:42:41 UTC; target coverage is item `msg_031c4f878d2513b9016ac0a2c66ae887d286fb7c8dd55d9946`, 2026-10-03 06:37:58 UTC.

### Architecture work and negative/censored outcomes

Tickets 28–32 formed the initial architecture cohort; 33–35 handled mixture and all-class fixed-batch learning; 36–40 implemented and closed the expanded fixed-batch mechanisms. The pinned index reports 384 reconciled stage receipts for the expanded set: seven treatments sustain the fixed-frame gate, while the sparse transformer has a valid negative result at the 10,000-update cap. Fine/coarse grid, ragged pillars, within-pillar attention, range fusion and sparse BEV are all admitted and evaluated as specified. They do not close original detection/segmentation/forecasting tasks or held-out comparisons. The question was not “can every encoder fit one frame?”—most can—but what survives equal-exposure, multi-scene evaluation and why.

A helpful correction in the interpretation is that deeper PFN adds only 4,224 parameters (~0.087%) and offers no faster sampled fit, so it is not a meaningful large-capacity test. Context PFN also changes masking/normalization. Grid choices alter support and stride; ragged pillars alter centroid and BN population; fine grouping hits a cap. Keep experimental factors separable and use support-specific errors/resource measurements to choose next interventions.

### Camera, SAM and Motion

The research program was grounded in Perception as its anchor dataset, with Motion and End-to-End Driving as distinct downstream suites. The paper progression was PointPillars → CenterPoint-style head control → SWFormer; camera baselines include FCOS3D then camera-to-BEV methods, with LET-3D-AP as metric; RSN was added as a range-view/hybrid direction. This was good hypothesis framing, not evidence of completed baselines. (Early program messages in root thread `01a0ee75…`; use precise receipts in full inventory if needed.)

R0 and the full103 sensor-data receipts support downstream engineering, but the overall acceptance still marks tickets 14–18 open. Later readiness audit found retained SAM evidence uses oracle prompts and measured projection incidence. It does not establish predicted-prompt semantic improvement or a same-prompt mask-vs-box comparison on identical eligible support. Geometry-aware mask-to-LiDAR transfer remains unclosed. Tickets 19–21 are also open, with an important nuance: the Motion foundation progressed substantially. Separate generation-pinned training/validation shards and extensions are mirrored and independently inventoried; native filename-key linkage, 11-step causal prefixes, future/key/duplicate refusal, observation-only camera-codebook features, native LiDAR decoding/calibrated XYZ, and a native oracle metric handoff each have separate live evidence. The oracle handoff validates metrics/labels, not a learned forecast. Ticket19 aggregate acceptance remains open and tickets20/21 still need model/protocol and held-out comparisons. This is useful pipeline completion with no forecasting efficacy claim.

Session-backed readiness check at 2026-10-04 05:04 UTC (root thread `01a0ee75…`, item `msg_031c4f878d2513b9016ac1de42927887d2a9d557b8263ef8b5`) recorded that PointPillars draft pins matched but its mean-APH rule needed reconciliation with the stronger every-class, two-sample gate, and SAM retained evidence had oracle-prompt limits. Treat that audit as a concrete protocol correction, not as completion.

### Tracking, migration and why work shifted toward infrastructure

A 24-definition experiment tracker and append-only research journal keep hypothesis, observation, decision and evidence-derived status distinct. Data acquisition and repeated optimization became expensive enough that reproducibility, scoring limits, checkpoint continuation, resource budgets, HDFS exact readback/recovery and retention were dependencies for safe further training—not peripheral polish. The balanced16 pilot had a confirmed 600-second native-score timeout after 19/21 gates; scoring-only recovery later passed all 21 stages, and a separately mounted GPU transition verifier passed exact 19→35 state/all-16-head comparison. Sustained-controller and rolling-retention admission were still open. The storage work was deliberately gated: several retained journal entries state that no optimizer updates or release were allowed until immutable checkpoint companions, source/resource identity, native/GPU state parity and independent HDFS recovery were complete. This explains why much of Oct 3–4 became infrastructure work; those steps were prerequisites, but they did not produce additional scientific model evidence.

First-class `sureal/models/` and `sureal/training/` was selected as the initial architecture ownership migration. Tickets44–48 specify frozen reference admission, first-class model/layer assembly, training policy/state, shared fixed-frame producer, and recovery/closeout. At cutoff the index says migration remained gated by written design/plan review, active implementation closeout and fresh live admission. Later reports say migration did not start. That was the correct interpretation: preserving old scientific runners/checkpoints and distinguishing fixed-frame from sustained sampling protects comparison validity. The collaboration-ticket49 work, accepted at cutoff, established local project/metadata foundations and did not close tickets44–48 or the detector questions.

## What worked and what should improve

The strongest practices were: source-pinned protocols and artifacts; independent live verifiers that reopen inputs rather than trusting producer `passed`; immutable failed/censored outcomes; explicit distinction between training-frame fit and held-out quality; full-native-GT scoring; no TF in the learned scientific runtime; exact trajectory/checkpoint and RNG replay; and retaining unresolved joins/labels instead of silently filling them. R0's full repeat and later 103-scene per-unit receipts make a strong engineering record.

The clearest avoidable rework was interpretation and admission order. Early PointPillars acceptance used mean populated-class APH, then had to be reconciled to the newer every-class two-consecutive-sample rule; freeze protocol and denominator before model work. Early all-class one-frame gates had low ranking power because almost all variants saturated in the same `(300,500]` interval; the investigation correctly pivoted toward mechanism controls and failure attribution, but future designs should budget for discriminatory multi-scene evidence from the start. The first balanced16 loss headline could have led to a false “successful training” conclusion; always report foreground/class/native metrics with total loss. Unequal exposure (125 visits/frame versus 500–750 on one frame) made architecture comparisons misleading until called out. Factor confounds (capacity, spatial propagation, support, masking, normalization) limited conclusions for the sparse-transformer and context/grid variants. Treat one-frame rank deltas as a hypothesis for follow-up, not a scientific direction verdict.

The next discriminating work is already represented by tickets 41–43 and the approved order: complete continuation/resource/HDFS admission for the frozen four sustained recipes; then run unchanged baseline/residual/class-balanced/prior-bias with per-frame visit and forgetting reports; build a measurement-indexed object failure ledger (assignment, support, box geometry, proposal survival/ranking, NMS, heading); run the frozen-weight balanced16 normalization/native-quality counterfactual before conditional pillar-LN; run association A0–A3 independently without mutating the frozen comparison recipes; finally require segment-held-out, multiseed architecture trials with equal exposure, full native GT, class/distance/support slices and resource costs. Camera/SAM and Motion need their own preregistered gates and predicted/casual-input controls. No proposed future result should be smuggled into the current status.

## Evidence and coverage note

Session-history discovery traversed the spawn-edge descendants of both supplied root threads (`01a0ee75-f519-7c80-b3c2-dc39d09e0b24` and `01a10073-9fd4-7361-b4f2-e7034230800a`): 32 distinct root/descendant IDs were discoverable, with items filtered at the specified cutoff. The stores are a projected local history, not a guarantee of all external/archived threads; some descendants are late collaboration reviews unrelated to science. For long sessions, the working extraction used public user/assistant messages and execution outcomes filtered by scientific topics, then checked all scientific claims against pinned Git documents and receipts. It did not quote private reasoning. Messages are supporting chronology, not scientific authority. Repository receipt aggregate and ticket status control where they qualify evidence; receipts that explicitly say “rehash,” “host reconciliation,” “preparation only,” “censored,” “oracle,” or “training-only” retain those limits.

The full ledger in `work-ledger.json` records lane/ticket, goal, status at cutoff, pinned source receipts, main finding and next discriminating experiment.
