# MAC effectiveness review: what it can fix, and what it cannot

**Cutoff:** 2026-10-04 18:56:47.276 UTC; repository base `a553645ef22761aa7708abf1ee109952a6cd2c38`. This review maps public user/assistant messages, native turn/error facts and committed evidence for the two assigned roots and descendants. The thread inventory covers 29 eligible threads by cutoff (23 implementation, 6 frontier, from the parent inventory); later retrospective-agent threads are out of scope. See [incident-mapping.json](incident-mapping.json) for precise incident-to-thread/turn/item anchors and testable indicators.

## Finding

The proposed Sureal-local multi-agent collaboration (MAC) is well targeted at repeated status reconstruction, manual cross-thread steering, task/worktree ownership ambiguity, stale-base integration and recovery from interrupted long sessions. Those problems arise because one lead currently reconstructs state from multiple sessions and manually coordinates an extended implementation stream. MAC’s strongest prospective value is coordination integrity and parallel preparation, not faster GPU science by default.

At the cutoff, that benefit is **not measured**: ticket49 is implemented, accepted and landed, but task50’s live runtime/stop/queue/tool/process capability gate is still open; tasks51–54 (including 53.0) and models/training44–48 are specified/planned. There is no actual two-worker overlap demonstration. The a553645 closeout documents that ticket49 has 62 prepared effects and 62 results, zero unresolved prepared effects, exact published mainline, clean canonical tree, and 2,399 raw artifact hashes reopened by the independent acceptance review. That is evidence the foundation/closeout worked; it is not evidence of MAC throughput or science acceleration.

## Incident mapping

The user repeatedly asked for implementation-worker state and how to relay instructions: see frontier items at 2026-10-03 16:39 and 16:54 UTC and 2026-10-04 16:32 and 18:52 UTC (exact IDs in I1). The committed task54 design addresses this with a read-only overview bound to exact task/spec/claim/attempt/thread/turn/worktree identities, evidence-linked summaries, source timestamps and explicit stale/coverage indicators. That could reduce manual status polling and relay; no reduction has been measured. The observer is explicitly unimplemented, and an inaccurate identity join or stale summary could worsen decisions, so the acceptance checks must independently reconcile every displayed card with Kata, Codex and controller facts.

Worktree and landing instructions were reiterated across the frontier and implementation threads: the user asked for a separate worker to land work at 19:57 on Oct 3, then clarified the landing trigger at 22:46 and 23:59; by 02:13 Oct 4, the requested protocol included exact-base task clones, immutable candidates, independent review and exact fast-forward landing. MAC’s claim/attempt binding, distinct worktrees, exact candidate review and serialized stale-base refusal map directly to those coordination risks. The residual is important: linked worktrees share Git refs/objects/config and provide cooperative file isolation only. Two active branches can still make one candidate stale, which means retaining C, refusing stale D, then refreshing and verifying E is an acceptance requirement, not an optional speed optimization. This protocol is also materially heavier than ad hoc branching.

The long implementation thread experienced a remote compaction turn recorded as `serverOverloaded`; the user explicitly directed resume from retained receipts rather than repeat work at 17:47 UTC Oct 4. Native state accounting supplied to this review counts 960 implementation turns (955 completed, 3 failed, 1 interrupted, 1 in progress), 60 compaction items and 6,759 command executions. These are activity counts, not wasted work, cost, or proof of a provider outage. The compaction turn’s stored duration of 27,804,061ms spans preceding work; it is not outage duration. Bounded attempts, exact checkpoints, durable effect receipts and preserved candidates could make recovery safer and reduce repeated effects. A lead can still build a huge session, and more threads cannot resolve service overload. The needed metric is duplicate external effects avoided and time to recover a known state under injected failures, not fewer turns.

Ticket49 demonstrates the value and cost of exact evidence/review. The closeout retained earlier failed receipts. The first closure wrappers used the wrong receipt shape; earlier post-audits exposed auditor/source-reference classification mistakes; and the landing operator review found four concrete gaps (review identity binding, safe output/lock scope, optimized-mode assertions, timeout evidence retention). A runtime probe also found the ticket50 plan’s byte-proxy assumption mismatched the installed WebSocket transport. These were corrected/reconciled before acceptance. This illustrates how an independent reviewer, source/runtime pins, live probes and immutable candidate binding can detect integration failures. It also shows that audits are fallible and expensive: independent role audits and thousands of cold-reopened artifacts are not free. MAC cannot reduce review effort below the science and evidence contract; measure first-pass acceptance and rework without weakening the independent gates.

## Limits and costs

**Data access:** The Sep 29 trace records no authorized Waymo copy in checked HDFS paths, anonymous bucket HTTP 401 and no host Google credential configuration. Later user-authenticated access enabled acquisition. A second worker could prepare schema/runtime checks while access is pending, but cannot grant authorization or discover data outside checked roots. Keep credentials outside briefs and runtime records.

**Resources:** A real preparation admission exceeded its 256 MiB component limit, and a derived-data retention pass proceeded through exact readback/recovery. The existing scientific budgets still include one exclusive GPU lock, GPU/RSS/raw/local-storage caps, and distinct training/evaluator budgets. Two seats do not mean two GPU jobs. MAC may improve utilization by pairing one long GPU job with a bounded CPU verifier, analysis or retention preparation; this is a hypothesis to compare against serial work per shared-GPU-hour. Starting simultaneous GPU treatments could lower throughput and break resource policy.

**Scientific validity:** A Motion pilot had eight valid ADE observations and six FDE endpoints because two targets lacked valid endpoints; the checker correctly kept those denominators distinct. Training traces also report class scores below the predeclared gate and a support diagnostic explicitly insufficient to explain the full vehicle gap. Concurrency cannot turn censored or confounded results into causal evidence. Better experiment selection, matched controls, denominator accounting and independent native scoring matter more than raw worker count.

**Contract/UI weight:** The MAC design requires exact identity and revision pins, effect journals, acknowledgements, stop proofs, retained rejected candidates, independent checks, recovery, resource ownership and a separate observer with freshness and coverage handling. This overhead is justified only if operational failures are contained and evidence is reusable. Failure states retain seats and can reduce apparent concurrency; false release is worse than slower throughput. The overview adds another source that can go stale. Benchmark the whole loop, including lead/auditor time and recovery, against a serial baseline.

**Independence:** Two workers may duplicate assumptions, read the same flawed analysis or compete for source-review attention. The second seat is not automatically an independent scientific opinion. Assign independent audits only with frozen candidate/input pins and a distinct check method; keep candidate producer separate from verifier.

## Practical acceleration plan

1. **Now, before MAC admission:** use a read-only/preparation lane if an independent Luna/analysis session is available, without sending it to or steering the implementation worker. It can inventory the remaining admitted research queue, prepare hypotheses and distinguishing predictions, inspect frozen evidence, draft CPU-only verifier plans, and identify ready tasks/resources. Treat all such outputs as proposals until pinned/reviewed; no source, queue, goal, resource, or scientific state change. This exploits currently available independent thinking without pretending managed dispatch exists.
2. **Honor the existing protocol gate order:** complete49’s landed closeout and prerequisites, then50 actual two-worker dispatch/stop proof, 51 candidate verification, 52 stale-base landing/recovery, 53.0 retention/cleanup foundation, 54 observability/live exercises, 53 final pilot, then 44→45→46→47→48. In particular, do not bypass task50’s installed-runtime WebSocket and full stop/queue/tool/process evidence, 53.0’s export/restore retention proof, or the existing scientific resource and continuation gates to start managed workers early.
3. **After admission, begin with bounded independent tasks:** choose two ready tasks with disjoint write/resource scopes and independently usable outputs. A productive first pattern is one long admitted GPU treatment (sole GPU owner) plus one CPU-only task on frozen inputs: verifier/fault-fixture work, source/evidence audit, hypothesis ledger or retention/recovery preparation. The CPU task must not mutate the active treatment or consume the same exclusive resource. Admit exact specs/plans and bases before dispatch; use explicit resource wait states.
4. **Preserve research sequencing:** keep the existing 42→43 order, 41.2 isolated with its ownership/literal-verification gate, and all resource/continuation/model migration gates. Keep models/training44–48 sequential as specified; parallelize only truly independent read-only preparation or verification around them, and refresh/revalidate any preparation made stale by a new source, runtime, treatment or base.
5. **Measure before claiming acceleration:** establish a serial baseline for time-to-decision, accepted deliverables, first-pass review, stale-preparation invalidation, lead/auditor effort, resource waits, GPU-hours, recovery actions and duplicate external effects. During pilot, require actual session overlap and exact ownership evidence; never use session count or turn count as a speedup proxy.

## Strongest conclusions

- The most direct MAC fit is repeated manual status/steering and cross-worktree ownership/landing coordination; exact identities and read-only evidence-linked status target those observed problems.
- Ticket49 shows that durable receipts, independent review and exact-source reopening can catch real defects; it also exposes substantial protocol/audit overhead and reviewer error, which MAC does not make disappear.
- Bounded tasks and effect reconciliation may contain compaction/transport interruptions, but the recorded `serverOverloaded` event does not establish a service outage duration or show that extra agents would help.
- Waymo access, HDFS/local storage, one shared GPU, scorer/runtime availability and strict evaluator/censoring rules are external/scientific limits; MAC can schedule around some waits but cannot remove them.
- No acceleration benefit has been measured. Begin with safe read-only preparation now, then admit managed work only in the stated order and compare completed, independently accepted scientific decisions per shared resource against a serial baseline.
