#define main inventory_fixture_main
#include "native_source_inventory.cc"
#undef main
#include <filesystem>
#include <array>
#include <map>
#include <cmath>
#include <limits>
#include <zlib.h>
using V=std::array<double,3>;using M=std::array<double,16>;
constexpr double tolerance=1e-6;
struct Image{int h,w,c;std::vector<double> values;double at(int r,int col,int channel)const{return values[(size_t(channel)*h+r)*w+col];}};
Image decode(const std::string&input){if(input.empty())throw std::runtime_error("missing component");std::string bytes(64*1024*1024,'\0');uLongf n=bytes.size();if(uncompress((Bytef*)bytes.data(),&n,(const Bytef*)input.data(),input.size())!=Z_OK)throw std::runtime_error("zlib bound");bytes.resize(n);waymo::open_dataset::DeltaEncodedData d;if(!d.ParseFromString(bytes))throw std::runtime_error("delta protobuf");known(d);auto&m=d.metadata();if(m.shape_size()!=3||m.quant_precision_size()!=m.shape(2))throw std::runtime_error("shape/precision");size_t total=1;for(auto dim:m.shape()){if(dim<1||dim>65535||total>32*1024*1024/size_t(dim))throw std::runtime_error("allocation cap");total*=dim;}for(auto q:m.quant_precision())if(!std::isfinite(q)||q<=0)throw std::runtime_error("precision");uint64_t coverage=0,ones=0;for(int j=0;j<d.mask_size();j++){coverage+=d.mask(j);if(j%2==0)ones+=d.mask(j);}if(coverage!=total||ones!=uint64_t(d.residual_size()))throw std::runtime_error("delta coverage");Image out{m.shape(0),m.shape(1),m.shape(2),std::vector<double>(total)};size_t index=0,pos=0;int64_t acc=0;for(int run=0;run<d.mask_size();run++)for(uint32_t k=0;k<d.mask(run);k++){int64_t val=0;if(run%2==0){auto x=d.residual(index++);if((x>0&&acc>std::numeric_limits<int64_t>::max()-x)||(x<0&&acc<std::numeric_limits<int64_t>::min()-x))throw std::runtime_error("delta overflow");acc+=x;val=acc;}double value=double(val)*double(m.quant_precision(pos/(size_t(out.h)*out.w)));if(!std::isfinite(value))throw std::runtime_error("decoded finite");out.values[pos++]=value;}return out;}
template<class T>M matrix(const T&t){if(t.transform_size()!=16)throw std::runtime_error("matrix shape");M m;std::copy(t.transform().begin(),t.transform().end(),m.begin());for(double x:m)if(!std::isfinite(x))throw std::runtime_error("matrix finite");for(int j=0;j<4;j++)if(std::abs(m[12+j]-(j==3?1.:0.))>1e-8)throw std::runtime_error("homogeneous row");for(int j=0;j<3;j++)for(int k=0;k<3;k++){double d=0;for(int r=0;r<3;r++)d+=m[4*r+j]*m[4*r+k];if(std::abs(d-(j==k?1.:0.))>1e-8)throw std::runtime_error("orthonormal");}double det=m[0]*(m[5]*m[10]-m[6]*m[9])-m[1]*(m[4]*m[10]-m[6]*m[8])+m[2]*(m[4]*m[9]-m[5]*m[8]);if(std::abs(det-1.)>1e-8)throw std::runtime_error("proper rotation");return m;}
V apply_pose(const M&m,const V&p){V out;for(int r=0;r<3;r++){out[r]=m[4*r+3];for(int c=0;c<3;c++)out[r]+=m[4*r+c]*p[c];}return out;}
V unapply(const M&m,const V&p){V out{};for(int c=0;c<3;c++)for(int r=0;r<3;r++)out[c]+=m[4*r+c]*(p[r]-m[4*r+3]);return out;}
V rpy(V p,double roll,double pitch,double yaw){double cr=std::cos(roll),sr=std::sin(roll),cp=std::cos(pitch),sp=std::sin(pitch),cy=std::cos(yaw),sy=std::sin(yaw);V rx{p[0],cr*p[1]-sr*p[2],sr*p[1]+cr*p[2]};V ry{cp*rx[0]+sp*rx[2],rx[1],-sp*rx[0]+cp*rx[2]};return {cy*ry[0]-sy*ry[1],sy*ry[0]+cy*ry[1],ry[2]};}
void close(V a,V b,double eps){for(int j=0;j<3;j++)if(!std::isfinite(a[j])||std::abs(a[j]-b[j])>eps)throw std::runtime_error("analytic geometry");}
void self_test(){double p=std::acos(-1.);close(rpy({1,2,3},p/2,p/2,p/2),{3,2,-1},1e-12);M m{0,-1,0,1,1,0,0,2,0,0,1,3,0,0,0,1};close(apply_pose(m,{4,5,6}),{-4,6,9},1e-12);close(unapply(m,{-4,6,9}),{4,5,6},1e-12);double a=((4.-.5)/4.*2.-1.)*p;close({2*std::cos(a),2*std::sin(a),0},{-std::sqrt(2.),std::sqrt(2.),0},1e-12);std::cout<<"PASS analytic RPY order, SE3 forward/inverse and polar-column convention\n";}
template<class T>T scalar(std::ifstream&f){T value;if(!f.read(reinterpret_cast<char*>(&value),sizeof(value)))throw std::runtime_error("truncated geometry stream");return value;}
void eof(std::ifstream&f){if(f.peek()!=EOF)throw std::runtime_error("extra geometry bytes");}
int main(int argc,char**argv){try{if(argc==2&&std::string(argv[1])=="--self-test"){self_test();return 0;}if(argc!=4)throw std::runtime_error("args source.pb geometry-dir report.tsv");auto size=std::filesystem::file_size(argv[1]);if(size>64*1024*1024)throw std::runtime_error("source cap");std::ifstream src(argv[1],std::ios::binary);auto bytes=read(src,size);waymo::open_dataset::Scenario s;if(!s.ParseFromString(bytes))throw std::runtime_error("scenario protobuf");known(s);if(s.current_time_index()!=10||s.timestamps_seconds_size()!=11||s.compressed_frame_laser_data_size()!=11||s.tracks_to_predict_size()!=0)throw std::runtime_error("causal prefix");for(int i=0;i<11;i++)if(!std::isfinite(s.timestamps_seconds(i))||(i&&s.timestamps_seconds(i)<=s.timestamps_seconds(i-1)))throw std::runtime_error("timeline");M current=matrix(s.compressed_frame_laser_data(10).pose());std::ofstream report(argv[3]);if(!report)throw std::runtime_error("report");report.precision(17);report<<"scenario_id\tframe\tlaser\treturn\tpoints\tmax_xyz_error_m\n";uint64_t total=0;int components=0;double worst=0;
for(int frame=0;frame<11;frame++){auto&f=s.compressed_frame_laser_data(frame);M vehicle=matrix(f.pose());std::map<int,const waymo::open_dataset::LaserCalibration*> calibs;for(auto&c:f.laser_calibrations())if(!calibs.emplace(c.name(),&c).second)throw std::runtime_error("duplicate calibration");if(calibs.size()!=5)throw std::runtime_error("calibration coverage");std::set<int> lasers;for(auto&laser:f.lasers()){int id=laser.name();if(id<1||id>5||!lasers.insert(id).second||!calibs.count(id))throw std::runtime_error("laser identity");auto&cal=*calibs.at(id);M extrinsic=matrix(cal.extrinsic());Image pixel_pose;if(id==1)pixel_pose=decode(laser.ri_return1().range_image_pose_delta_compressed());for(int ret=1;ret<=2;ret++){auto&r=ret==1?laser.ri_return1():laser.ri_return2();auto image=decode(r.range_image_delta_compressed());if(image.c!=4||(id==1&&(pixel_pose.c!=6||pixel_pose.h!=image.h||pixel_pose.w!=image.w)))throw std::runtime_error("range/pose shape");if(cal.beam_inclinations_size()!=0&&cal.beam_inclinations_size()!=image.h)throw std::runtime_error("inclination support");std::string stem=std::string(argv[2])+"/"+std::to_string(frame)+"-"+std::to_string(id)+"-"+std::to_string(ret)+"-range";std::ifstream xyz(stem+".xyz.bin",std::ios::binary),pixels(stem+".pixels.bin",std::ios::binary),features(stem+".features.bin",std::ios::binary);if(!xyz||!pixels||!features)throw std::runtime_error("missing geometry stream");uint64_t count=0;double maximum=0;for(int row=0;row<image.h;row++)for(int col=0;col<image.w;col++){double range=image.at(row,col,0);if(range<=0)continue;int reversed=image.h-1-row;double inc=cal.beam_inclinations_size()?cal.beam_inclinations(reversed):(double(reversed)+.5)/image.h*(cal.beam_inclination_max()-cal.beam_inclination_min())+cal.beam_inclination_min();if(!std::isfinite(inc)||(!cal.beam_inclinations_size()&&cal.beam_inclination_min()>cal.beam_inclination_max()))throw std::runtime_error("inclination finite/bounds");double az=((double(image.w-col)-.5)/image.w*2.-1.)*std::acos(-1.)-std::atan2(extrinsic[4],extrinsic[0]);V local{range*std::cos(inc)*std::cos(az),range*std::cos(inc)*std::sin(az),range*std::sin(inc)};V world=apply_pose(extrinsic,local);if(id==1){world=rpy(world,pixel_pose.at(row,col,0),pixel_pose.at(row,col,1),pixel_pose.at(row,col,2));for(int j=0;j<3;j++)world[j]+=pixel_pose.at(row,col,j+3);}else world=apply_pose(vehicle,world);V expected=unapply(current,world),actual;for(int j=0;j<3;j++){actual[j]=scalar<double>(xyz);if(!std::isfinite(actual[j]))throw std::runtime_error("XYZ finite");double error=std::abs(actual[j]-expected[j]);maximum=std::max(maximum,error);
#ifndef OMIT_GEOMETRY_CHECK
if(error>tolerance)throw std::runtime_error("XYZ mismatch frame="+std::to_string(frame)+" laser="+std::to_string(id)+" return="+std::to_string(ret));
#endif
}int rr=scalar<int32_t>(pixels),cc=scalar<int32_t>(pixels);if(rr!=row||cc!=col)throw std::runtime_error("pixel key mismatch");for(int j=0;j<3;j++){float got=scalar<float>(features),expected_feature=float(image.at(row,col,j));if(!std::isfinite(got)||got!=expected_feature)throw std::runtime_error("physical feature mismatch");}count++;}eof(xyz);eof(pixels);eof(features);total+=count;worst=std::max(worst,maximum);components++;report<<s.scenario_id()<<'\t'<<frame<<'\t'<<id<<'\t'<<ret<<'\t'<<count<<'\t'<<maximum<<'\n';}}if(lasers.size()!=5)throw std::runtime_error("laser coverage");}if(components!=110||!report)throw std::runtime_error("component coverage/report");std::cout<<"VERIFIED "<<s.scenario_id()<<" returns="<<components<<" points="<<total<<" max_xyz_error_m="<<worst<<" tolerance_m="<<tolerance<<"\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
