"""Materialize selected native labels and admit source/target coverage live."""
import hashlib,json,subprocess,sys
from pathlib import Path
PACKAGE=Path(__file__).resolve().parents[1];sys.path.insert(0,str(PACKAGE))
from insula.entry import launch_plan
from pipeline.staged_source import staged_source
from pipeline.training_box_replay import retained_raw_bytes
from insula.runtime_identity import verify_rootfs
from balanced import coverage_summary
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
cache=Path.home()/'.cache/waystone/waymo-perception';root=cache/'insula/rootfs-v2';lock=json.loads(Path(str(root)+'.lock.json').read_text());verify_rootfs(root,lock['rootfs_sha256']);candidate_path=PACKAGE/'research/balanced16-selection.candidate.json';candidate=json.loads(candidate_path.read_text());candidate_sha=sha(candidate_path);workers=PACKAGE/'cohort';pins={str(p):sha(p) for p in workers.glob('*.py')};base=cache/'scientific-processing/balanced16-labels-v2';base.mkdir();retained=retained_raw_bytes(cache,PACKAGE);complete=[];coveredframes=[]
for scene in sorted({f['identity'].split(':')[0] for f in candidate['frames']}):
 selection=[f for f in candidate['frames'] if f['identity'].split(':')[0]==scene];record=json.loads((cache/'scientific-source-audit'/f'training-lidar_box-{scene}.json').read_text());destination=base/scene;destination.mkdir();inputs=destination/'input';inputs.mkdir();job={'scene':scene,'timestamps':[int(f['identity'].split(':')[1]) for f in selection],'source':record};(inputs/'job.json').write_text(json.dumps(job));checks=[]
 def live(worker,src,out,args=None,extra=None):
  out.mkdir();command=launch_plan(root,PACKAGE,src,out,args or ['python','/tmp/workers/'+worker]);i=command.index('--');command[i:i]=['--ro-bind',str(workers),'/tmp/workers','--ro-bind',str(inputs),'/tmp/input',*(extra or [])];result=subprocess.run(command,capture_output=True,text=True,timeout=600);(out/'live.log').write_text(result.stdout+result.stderr);assert result.returncode==0,(worker,result.stderr);checks.append({'command':command,'exit_code':0})
 with staged_source(record,cache,retained_bytes=retained,limit_bytes=2*1024**3,transfer_command=['timeout','--kill-after=5s','120s',sys.executable,str(workers/'gcs_metadata_get.py')]) as (raw,transfer):
  produced=destination/'producer';live('overfit-box-worker.py',raw.parent,produced,args=['python','/tmp/workers/overfit-box-worker.py','producer']);live('overfit-box-worker.py',raw.parent,destination/'reference',args=['python','/tmp/workers/overfit-box-worker.py','reference'],extra=['--ro-bind',str(produced),'/tmp/produced'])
 templates=json.loads((PACKAGE/'research/training-anchor-templates.candidate.json').read_text())['templates'];job.update(boxes_sha256=sha(produced/'targets.json'),selection=selection,templates=[t['values'] for t in templates]);(inputs/'job.json').write_text(json.dumps(job));targetdir=destination/'targets';live('targets.py',produced,targetdir);frames=json.loads((targetdir/'check.json').read_text())['frames'];coveredframes.extend(dict(f,objects=f['covered_objects']) for f in frames);assert sha(candidate_path)==candidate_sha and all(sha(p)==h for p,h in pins.items());receipt={'checks':checks,'runtime_lock':lock,'selection_sha256':candidate_sha,'transfer':transfer,'worker_hashes':pins,'artifacts':{str(p):sha(p) for p in destination.rglob('*') if p.is_file()}};(destination/'receipt.json').write_text(json.dumps(receipt,indent=2));complete.append({'scene':scene,'receipt':str(destination/'receipt.json'),'sha256':sha(destination/'receipt.json')});print('ADMITTED LABELS',scene,flush=True)
result={'selection_sha256':candidate_sha,'scene_receipts':complete,'covered_object_coverage':coverage_summary(coveredframes),'scope':'source-equivalent native labels and production anchor coverage; independent literal target audit and physical support still required'};(PACKAGE/'research/balanced16-labels-and-anchor-coverage.json').write_text(json.dumps(result,indent=2)+'\n');print('COVERED',result['covered_object_coverage'],flush=True)
