SUSTAINED_RUN_SOURCE_GLOBS = [
    "cohort/**/*.py",
    "pipeline/**/*.py",
]

SUSTAINED_CHECKPOINT_RETENTION_HOST_SOURCES = [
    "cohort/checkpoint_retention_audit.py",
    "cohort/checkpoint_retention_policy.py",
    "cohort/checkpoint_retention_sources.py",
    "cohort/publish_sustained_checkpoint.py",
    "cohort/sustained_checkpoint_inventory.py",
    "cohort/sustained_controller_lock.py",
    "evidence/source_snapshot.py",
    "//autonomy/insula:host_entry_runtime_py",
    "resources/resource_archive.py",
    "resources/resource_archive_cli.py",
    "resources/resource_rehydrate.py",
    "resources/resource_release_plan.py",
    "resources/scientific_budget.py",
    "resources/scientific_payload.py",
]

SUSTAINED_PILOT_RETENTION_HOST_SOURCES = [
    "cohort/pilot_retention_audit.py",
    "cohort/pilot_retention_sources.py",
    "cohort/publish_sustained_pilot.py",
    "cohort/sustained_pilot_inventory.py",
    "evidence/source_snapshot.py",
    "//autonomy/insula:host_entry_runtime_py",
    "resources/resource_archive.py",
    "resources/resource_archive_cli.py",
    "resources/resource_rehydrate.py",
    "resources/resource_release_plan.py",
    "resources/scientific_budget.py",
    "resources/scientific_payload.py",
]

NATIVE_CACHE_RETENTION_HOST_SOURCES = [
    "cohort/cache_inventory.py",
    "cohort/cache_retention_audit.py",
    "cohort/publish_native_cache.py",
    "cohort/retention_sources.py",
    "evidence/source_snapshot.py",
    "//autonomy/insula:host_entry_runtime_py",
    "resources/resource_archive.py",
    "resources/resource_archive_cli.py",
    "resources/resource_rehydrate.py",
    "resources/resource_release_plan.py",
    "resources/scientific_budget.py",
    "resources/scientific_payload.py",
]

SUSTAINED_CONTROLLER_HOST_SOURCES = [
    "cohort/checkpoint_retention_audit.py",
    "cohort/checkpoint_retention_policy.py",
    "cohort/checkpoint_retention_sources.py",
    "cohort/publish_sustained_checkpoint.py",
    "cohort/run_sustained.py",
    "cohort/sustained_admission.py",
    "cohort/sustained_checkpoint_inventory.py",
    "cohort/sustained_contract.py",
    "cohort/sustained_control.py",
    "cohort/sustained_controller_backend.py",
    "cohort/sustained_controller_lock.py",
    "cohort/sustained_controller_sources.py",
    "cohort/sustained_scoring_budget.py",
    "cohort/sustained_sources.py",
    "cohort/sustained_stage_inputs.py",
    "cohort/sustained_workflow.py",
    "evidence/source_snapshot.py",
    "//autonomy/insula:host_entry_runtime_py",
    "resources/resource_archive.py",
    "resources/resource_archive_cli.py",
    "resources/resource_rehydrate.py",
    "resources/resource_release_plan.py",
    "resources/scientific_budget.py",
    "resources/scientific_payload.py",
    "studies/architecture/experiment_runner.py",
]
