SUSTAINED_RUN_SOURCE_GLOBS = [
    "dataset/**/*.py",
    "geometry/**/*.py",
]

SUSTAINED_CHECKPOINT_RETENTION_HOST_SOURCES = [
    "//autonomy/retention:checkpoint_retention_policy.py",
    "//autonomy/retention:publication.py",
    "//autonomy/retention:publication_sources.py",
    "//autonomy/retention:publish_sustained_checkpoint.py",
    "//autonomy/retention:publisher_runtime.py",
    "//autonomy/retention:sustained_checkpoint_inventory.py",
    "//autonomy/retention:sustained_controller_lock.py",
    "//autonomy/blob_store:core.py",
    "//autonomy/evidence:source_snapshot_py",
    "//autonomy/insula:runtime_identity.py",
    "//autonomy/resources:backend.py",
    "//autonomy/resources:scientific_budget.py",
    "//autonomy/resources:scientific_payload.py",
]

SUSTAINED_PILOT_RETENTION_HOST_SOURCES = [
    "//autonomy/retention:publication.py",
    "//autonomy/retention:publication_sources.py",
    "//autonomy/retention:publish_sustained_pilot.py",
    "//autonomy/retention:publisher_runtime.py",
    "//autonomy/retention:sustained_controller_lock.py",
    "//autonomy/retention:sustained_pilot_inventory.py",
    "//autonomy/blob_store:core.py",
    "//autonomy/evidence:source_snapshot_py",
    "//autonomy/resources:scientific_budget.py",
    "//autonomy/resources:scientific_payload.py",
]

NATIVE_CACHE_RETENTION_HOST_SOURCES = [
    "//autonomy/retention:cache_inventory.py",
    "//autonomy/retention:publication.py",
    "//autonomy/retention:publication_sources.py",
    "//autonomy/retention:publish_native_cache.py",
    "//autonomy/retention:publisher_runtime.py",
    "//autonomy/retention:sustained_controller_lock.py",
    "//autonomy/blob_store:core.py",
    "//autonomy/evidence:source_snapshot_py",
    "//autonomy/resources:scientific_budget.py",
    "//autonomy/resources:scientific_payload.py",
]

SUSTAINED_CONTROLLER_HOST_SOURCES = [
    "//autonomy/retention:checkpoint_retention_policy.py",
    "//autonomy/retention:publication.py",
    "//autonomy/retention:publication_sources.py",
    "//autonomy/retention:publish_sustained_checkpoint.py",
    "//autonomy/retention:publisher_runtime.py",
    "//autonomy/retention:sustained_checkpoint_inventory.py",
    "//autonomy/retention:sustained_controller_lock.py",
    "//autonomy/resources:backend.py",
    "//autonomy/resources:checkpoint.py",
    "//autonomy/resources:command.py",
    "//autonomy/resources:execute_worker.py",
    "//autonomy/resources:kernel_scope.py",
    "//autonomy/resources:process_lifecycle.py",
    "//autonomy/resources:scoped_stage.py",
    "//autonomy/resources:sources.py",
    "//autonomy/resources:stage.py",
    "//autonomy/resources:stage_accounting.py",
    "//autonomy/training_execution:run_sustained.py",
    "//autonomy/training_execution:sustained_admission.py",
    "//autonomy/detection:sustained_contract.py",
    "//autonomy/training_execution:sustained_control.py",
    "//autonomy/training_execution:sustained_controller_backend.py",
    "//autonomy/training_execution:sustained_controller_sources.py",
    "//autonomy/resources:sustained_scoring_budget.py",
    "//autonomy/training_execution:sustained_sources.py",
    "//autonomy/training_execution:sustained_stage_inputs.py",
    "//autonomy/training_execution:sustained_workflow.py",
    "//autonomy/evidence:source_snapshot_py",
    "//autonomy/insula:host_entry_runtime_py",
    "//autonomy/resources:resource_archive.py",
    "//autonomy/resources:resource_archive_cli.py",
    "//autonomy/resources:resource_rehydrate.py",
    "//autonomy/resources:resource_release_plan.py",
    "//autonomy/resources:scientific_budget.py",
    "//autonomy/resources:scientific_payload.py",
    "//autonomy/studies:architecture/experiment_runner.py",
]
